# Generated by Django 5.1.1 on 2024-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereal', '0004_contact_rename_message_about_bio_remove_about_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('name_2', models.CharField(blank=True, max_length=225, null=True)),
                ('bio_2', models.TextField(blank=True, null=True)),
                ('name_3', models.CharField(blank=True, max_length=225, null=True)),
                ('bio_3', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ethereal',
        ),
    ]
